{
    'name': "Bluemax Default Address",
    'version': "16.0.1.0,0",
    'summary': """""",
    'description': """""",
    'author': "BlueMax",
    'company': 'BlueMax',
    'maintainer': 'BlueMax',
    'website': 'https://www.nckwebtech.com/',
    'category': 'Report',
    'depends': ['base','base_setup'],
    'data': [
            'views/res_config_settings.xml',
    ],
    'images': [],
    'license': "AGPL-3",
    'installable': True,
    'application': True,
    # 'price': 78.50,
    # 'currency': 'USD',
}
